#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */

define('YII_ENV', trim(file_get_contents('.env')));

define('YII_ENV_DEV', 'development');
define('YII_ENV_PROD', 'production');

define('YII_DEBUG', YII_ENV !== YII_ENV_PROD);

require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/vendor/yiisoft/yii2/Yii.php';

$config = require(__DIR__ . '/config/console-' . YII_ENV . '.php');

$application = new yii\console\Application($config);
$exitCode = $application->run();

exit($exitCode);
